### ISSUE TITLE
Pesquisar sobre Sites para auxiliar grandes eventos

### ISSUE THREAD

**Issue by PacoGuimaraes** [Projetos-de-Extensao/PFE_24.2_8001_III_Pandora#1]
- [x]  Procurar por sites semelhantes

- [x] Pode escolher um tema(evento) ou Copa do Mundo Feminina

- [x] Principais funcionalidades

- [x] Principais serviços a serem apresentados (Restaurante, hospital, etc)

- [x] Criar um arquivo pesquisa.md na pasta /dos/base

**Comment by yagoduarte0** [comment]
Atualizando a ISSUE com as 5 tarefas feitas no arquivo pesquisa.md

https://github.com/Projetos-de-Extensao/PFE_24.2_8001_III_BJJ/blob/main/docs/base/pesquisa.md
